name: Build Pygame for Web

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        python3 -m pip install --upgrade pip
        python3 -m pip install pygame pyinstaller

    - name: Build Project
      run: |
        pyinstaller --onefile src/game.py
        mkdir -p build
        mv dist/game build/
        cp public/index.html build/index.html

    - name: Deploy to GitHub Pages (Optional)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

