name: Build Pygame for Web

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame-wasm

    - name: Build for Web
      run: |
        mkdir -p build
        python -m pygame_wasm build src/game.py -o build
        cp public/index.html build/index.html

    - name: Deploy to GitHub Pages (Optional)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
